---
deployment:
  tasks:
    - export DEPLOYPATH=/home/homesliceweb/cors-anywhere.homesliceweb.com/web-app
    - /bin/cp -R lib $DEPLOYPATH
    - /bin/cp .eslintignore $DEPLOYPATH
    - /bin/cp .eslintrc $DEPLOYPATH
    - /bin/cp .gitignore $DEPLOYPATH
    - /bin/cp server.js $DEPLOYPATH
    - /bin/cp package.json $DEPLOYPATH
    - /bin/cp package-lock.json $DEPLOYPATH
    - cd $DEPLOYPATH
    - npm install