---
deployment:
  tasks:
    - export DEPLOYPATH=/home2/homesliceweb/cors-anywhere.homesliceweb.com/web-app
    - /bin/cp -R bin $DEPLOYPATH
    - /bin/cp -R public $DEPLOYPATH
    - /bin/cp -R routes $DEPLOYPATH
    - /bin/cp -R views $DEPLOYPATH
    - /bin/cp .gitignore $DEPLOYPATH
    - /bin/cp app.js $DEPLOYPATH
    - /bin/cp package.json $DEPLOYPATH
    - /bin/cp package-lock.json $DEPLOYPATH
    - cd $DEPLOYPATH
    - npm install